$(document).ready(function(){
	$("#hideButton").click(function(){
		$("img").toggle();
	});
});
$(document).ready(function(){
	$("#toggleButton").click(function(){
		$("img").toggle();
	});
});
$(document).ready(function(){
	$("#backButton").click(function(){
		$("img").toggle();	
	});
});
$(document).ready(function(){
	$("#frontButton").click(function(){
		$("img").toggle();	
	});
});		
$(document).ready(function(){
	$("#showButton").click(function(){
		$("img").toggle();
	});
});